DYNAXCEL/urls.py
from django.contrib import admin
from django.urls import path,include
from WebApp import views as WebView
from WebApp import urls as WebUrls
from WebAdmin import urls as WebAdminUrls


from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('default-admin/', admin.site.urls),
    path('', WebView.index, name="index"),
    path('web/', include(WebUrls)),
    path('admin/', include(WebAdminUrls)),
    path('accounts/login/', WebAdminUrls.login, name="login"),
    path('logout/', WebAdminUrls.logout, name="logout"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WebAdmin/urls.py
from django.urls import path
from .views import * 

urlpatterns = [ 
    path('dashboard', dashboard, name="admin_dashboard"), 

    path('career_list/', career_list, name='admin_career_list'),
    path('create_career/', create_career, name='admin_create_career'),
    path('update_career/<int:id>', update_career, name="admin_update_career"), 
    path('delete_career/<int:id>', delete_career, name="admin_delete_career"), 

    path('job_application_list/', job_application_list, name="admin_job_application_list"), 
    path('delete_job_applicattion/<int:id>', delete_job_applicattion, name="admin_delete_job_applicattion"), 

    path('certificate_list', certificate_list, name="certificate_list"),
    path('create_certificate', create_certificate, name="create_certificate"),
    path('delete_certificate/<int:id>', delete_certificate, name="delete_certificate"),

    path('photo_gallery_category_list', photo_gallery_category_list, name="photo_gallery_category_list"), 
    path('create_photo_category_for_gallery', create_photo_category_for_gallery, name="create_photo_category_for_gallery"), 
    path('delete_category/<int:id>', delete_category, name="delete_category"), 

    path('photo_gallery_list', photo_gallery_list, name="photo_gallery_list"), 
    path('create_photo_for_gallery', create_photo_for_gallery, name="create_photo_for_gallery"), 
    path('delete_photo_from_gallery/<int:id>', delete_photo_from_gallery, name="delete_photo_from_gallery"), 
    # video Gallary
    path('video_gallery_list', video_gallery_list, name="video_gallery_list"), 
    path('create_video_for_gallery', create_video_for_gallery, name="create_video_for_gallery"), 
    path('delete_video_from_gallery/<int:id>', delete_video_from_gallery, name="admin_delete_video_from_gallery"), 

    path('enquiry_list', enquiry_list, name="admin_enquiry_list"), 
    path('delete_enquiry/<int:id>', delete_enquiry, name="admin_delete_enquiry"), 

    path('news_list/', news_list, name='admin_news_list'),
    path('create_news/', create_news, name='admin_create_news'),
    path('update_news/<int:id>/', update_news, name='admin_update_news'),
    path('delete_news/<int:id>/', delete_news, name='admin_delete_news'),
    path('create_news_photos_videos/', create_news_photos_videos, name='admin_create_news_photos_videos'),
    path('news_details/<int:id>/', news_details, name='admin_news_details'),
    path('delete_news_photos/<int:id>/', delete_news_photos, name='admin_delete_news_photos'),
    path('delete_news_video/<int:id>/', delete_news_video, name='admin_delete_news_video'),

]

WebApp/urls.py
 
from django.urls import path
from WebApp.views import  *
urlpatterns = [
    path('contact-us', contact_us, name="website_contact_us"),
    path('about_us', about_us, name="website_about_us"),
    path('career', career, name="website_career"),
    path('career_apply_job', career_apply_job, name="career_apply_job"),
    path('infrastructure', infrastructure, name="website_infra"),
    path('web_news', web_news, name="web_news"),
    path('web_news_details/<int:id>', web_news_details, name="web_news_details"),
    path('career', career, name="website_career"),
    path('create_career_application', create_career_application, name="create_career_application"),

    path('career_apply_job/<int:id>', career_apply_job, name="career_apply_job"),
    path('sustainability', sustainability, name="sustainability"),
    path('certificates', certificates, name="web_certificates"),
    path('photos_gallary', web_photos_gallary, name="web_photos_gallary"),
    path('videos_gallary', web_videos_gallary, name="web_videos_gallary"),


    path('services_stainless_steel', stainless_steel, name="stainless_steel"),
    path('services_ASME_PED_Vessels', services_ASME_PED_Vessels, name="services_ASME_PED_Vessels"),
    path('services_railway_metro', services_railway_metro, name="services_railway_metro"),
    path('services_food_farma', services_food_farma, name="services_food_farma"),
    path('services_psa_based', services_psa_based, name="services_psa_based"),
    path('services_defence_equipements', services_defence_equipements, name="services_defence_equipements"),

    path('services_mining', services_mining, name="services_mining"),
    path('services_paper', services_paper, name="services_paper"),
    path('services_power', services_power, name="services_power"),
    path('services_textiles', services_textiles, name="services_textiles"),


]

WebAdmin/models.py
from django.db import models
import os

# Create your models here.

class Certificate(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='website/certs/')
    pdf = models.FileField(upload_to='website/certs/')
    
    def __str__(self):
        return self.title
    

    
class PhotoGalleryCategories(models.Model):
    category_name = models.CharField(max_length=255) 
 
    def __str__(self):
        return f"{self.category_name}"

class PhotoGallery(models.Model):
    category = models.ForeignKey(PhotoGalleryCategories, on_delete=models.CASCADE, related_name='photos')
    caption = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="photo_gallery/")
    is_show_on_home_page = models.BooleanField(null=True)

    def delete(self, *args, **kwargs):
        # Delete the image file from the filesystem
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super(PhotoGallery, self).delete(*args, **kwargs)

    def __str__(self):
        return f"{self.caption} Image"

class VideoGallery(models.Model): 
    caption = models.CharField(max_length=255, blank=True, null=True)
    video_link = models.CharField(blank=True, null=True, help_text="Enter YouTube video link", max_length=255)
  

 
class Career(models.Model):
    title = models.CharField(max_length=255)
    location = models.CharField(max_length=100)
    posted_on = models.DateField(auto_now_add=True)
    vacancy = models.IntegerField()
    desired_qualification = models.TextField()
    experience_required = models.TextField()
    career_description = models.TextField()
    roles_responsibility = models.TextField()
    skills_required = models.TextField()
    is_publish=models.BooleanField(default=True)
    def __str__(self):
        return self.title

class CareerApplication(models.Model):
    career = models.ForeignKey(Career, on_delete=models.CASCADE, related_name='applications')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    resume = models.FileField(upload_to='resumes/')
    date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return f'{self.name} - {self.career.title}'
    

class Enquiry(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateField(auto_now_add=True,null=True)

    def __str__(self):
        return f"{self.name} - {self.subject}"
    
class News(models.Model):
    title=models.CharField(max_length=200) 
    content=models.TextField()
    thumbnail = models.ImageField(upload_to="news_thumbnail/",  help_text="Recommended Size 1280 x 720 (landscape)", blank=True, null=True)
    is_active = models.BooleanField(default=True)
    date=models.DateField(null=True, auto_now=False, auto_now_add=False)
    def __str__(self):
        return self.title
    
    
class NewsPhotosVideos(models.Model):
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="news_photos/", blank=True, null=True)
    video_link = models.CharField(blank=True, null=True, help_text="Enter YouTube video link", max_length=255)
    def __str__(self):
        return f"{self.news.title} Photos and Videos"

    def get_youtube_embed_url(self):
        if self.video_link:
            video_id = self.get_video_id()
            print(video_id)
            return f"https://www.youtube.com/embed/{video_id}"
        return None

    def get_video_id(self):
        if self.video_link:
            return self.video_link.split('v=')[-1]
        return None

    def video_thumbnail(self):
        if self.video_link:
            video_id = self.get_video_id()
            return f"https://img.youtube.com/vi/{video_id}/0.jpg"
        return None

    

WebAdmin/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms  import AuthenticationForm
from django_summernote.widgets import SummernoteWidget
from django.core.exceptions import ValidationError
from PIL import Image
import io


class login_form(AuthenticationForm):
    username=forms.CharField(label='username',widget=forms.TextInput(attrs={'class':'username','placeholder':'Enter Username'}))
    password=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'username','placeholder':'Enter Password'}))


class PhotoGalleryCategoriesForm(forms.ModelForm):
    class Meta:
        model = PhotoGalleryCategories
        fields = ['category_name'] 


class PhotoGalleryForm(forms.ModelForm):
    class Meta:
        model = PhotoGallery
        fields = ['category','caption', 'image','description','is_show_on_home_page']
        widgets = {
            'description': forms.Textarea(attrs={
                'class': 'form-control',  # Optional Bootstrap class for styling
                'rows': 4,  # Set the height to 4 lines
                'placeholder': 'Enter a short description...',  # Optional placeholder
            }),
        }
 
class CertificateForm(forms.ModelForm):
    class Meta:
        model = Certificate
        fields = ['title', 'description', 'image', 'pdf']
        widgets = {
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 4,
                'placeholder': 'Enter a short description...',
            }),
        }


class VideoGalleryForm(forms.ModelForm):
    class Meta:
        model = VideoGallery
        fields = ['caption', 'video_link']




class CareerForm(forms.ModelForm):
    class Meta:
        model = Career
        fields = [
            'title', 'location', 'vacancy', 'desired_qualification',
            'experience_required', 'career_description', 'roles_responsibility', 'skills_required','is_publish'
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}), 
            'vacancy': forms.NumberInput(attrs={'class': 'form-control'}),
            'experience_required': forms.TextInput(attrs={'class': 'form-control'}), 
            
            'desired_qualification': forms.Textarea(attrs={'class': 'summernote form-control', 'data-height': '100'}),
            'career_description': forms.Textarea(attrs={'class': 'summernote form-control', 'data-height': '300'}),
            'roles_responsibility': forms.Textarea(attrs={'class': 'summernote form-control', 'data-height': '200'}),
            'skills_required': forms.Textarea(attrs={'class': 'summernote form-control', 'data-height': '200'}),
            
            'is_publish': forms.CheckboxInput(attrs={'class': 'form-check-input', 'style': 'margin-left:10px;'}),

        }

    
class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'content', 'thumbnail', 'date', 'is_active']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'content': forms.Textarea(attrs={'class': 'summernote form-control', 'data-height': '100'}),
        }
 
    

class NewsPhotosVideosForm(forms.ModelForm):
    class Meta:
        model = NewsPhotosVideos
        fields = ['news', 'image','video_link']
        

WebAdmin/templates/admin_certificate_list.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Certificates</h1>
        <div class="row">
            <div class="col"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="container" style="max-width:97%;">
                <div class="text-lg-end text-start">
                    <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#create_certificate">
                        <i class="mdi mdi-file-pdf"></i> Add New
                    </a>
                </div>
            </div>
        </div>
    </div>
    <hr>

    <!-- Modal for Create Certificate -->
    <div class="modal fade" id="create_certificate" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
            <div class="modal-content">
                <div class="modal-header bg-gradient-primary text-light">
                    <h5 class="modal-title" id="exampleModalLongTitle">Create Certificate</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'create_certificate' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                {{ certificate_form|crispy }}
                            </div>
                        </div>
                        <hr>
                        <center>
                            <input type="submit" id="btnCreateSubmit" value="Submit" class="btn bg-gradient-primary text-light">
                        </center>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Certificate List -->
    <section class="section dashboard">
        <div class="row">
            <div class="col-lg-12">
                <div style="padding:2%">
                    <div style="overflow:scroll;">
                        <table id="example" class="table table-striped" style="width:100%; min-width: max-content;">
                            <thead>
                                <tr style="background:#02B4C3;">
                                    <th class="text-center text-white">Sr.No</th>
                                    <th class="text-center text-white">Title</th>
                                    <th class="text-center text-white">PDF</th>
                                    <th class="text-center text-white">Image</th>
                                    <th class="text-center text-white">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if certificate_data %}
                                    {% for cert in certificate_data %}
                                        <tr>
                                            <td class="text-center">{{ forloop.counter }}</td>
                                            <td class="text-center">{{ cert.title }}</td>
                                            <td class="text-center">
                                                {% if cert.pdf %}
                                                    <a href="{{ cert.pdf.url }}" target="_blank">View PDF</a>
                                                {% else %}
                                                    N/A
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                {% if cert.image %}
                                                    <img src="{{ cert.image.url }}" alt="Certificate Image" style="max-height:60px;">
                                                {% else %}
                                                    N/A
                                                {% endif %}
                                            </td>
                                            <td class="text-center">
                                                <a href="{% url 'delete_certificate' cert.id %}" class="btn btn-danger px-3">Delete</a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr><td colspan="5" class="text-center">No certificates found.</td></tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
    $(document).ready(function () {
        $('.summernote').each(function () {
            const customHeight = $(this).data('height') || 300;
            $(this).summernote({
                height: customHeight,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['insert', ['link', 'picture']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ]
            });
        });
    });
</script>
{% endblock %}

WebAdmin/templates/admin_news_list.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    #id_content {
        height: 100px;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    } 
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 100px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        border-radius:10px;
    }
    .dropdown-content a {
        color: black;
        padding: 5px 10px;
        text-decoration: none;
        display: block;
        text-align: left;
    }
    .dropdown-content a:hover {background-color: #f1f1f1;}
    .dropdown:hover .dropdown-content {
        display: block;
    } 
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>News</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->

    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="container" style="max-width:97%;">
                    <div class="text-lg-end text-start">
                        <!-- Use text-lg-end for right alignment in large screens -->
                        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#filter_data"><i
                                class="mdi mdi-filter"></i> Filter</a>
                        
                        
                                <div class="dropdown">
                                    <button class="dropbtn btn btn-primary dropdown-toggle">Export</button>
                                    <div class="dropdown-content">
                                        <a href="#">PDF</a>
                                        <a href="#">CSV</a>
                                        <a href="#">Excel</a>
                                    </div>
                                </div>
                               
                                
                            <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#create_news"><i
                                class="mdi mdi-file-pdf"></i> Add New</a>
 
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>



    <div class="modal fade" id="create_news" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width:1000px;">
            <div class="modal-content">
                <div class="modal-header bg-gradient-primary text-light ">
                    <h5 class="modal-title" id="exampleModalLongTitle">Create News</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <form method="post" action="{% url "admin_create_news" %}"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    {{news_form|crispy}}
                                </div>
                                 
                            </div>
                            <hr>
                            <center>
                                <input type="submit" id="btnCreateSubmit" value="Submit"
                                    class="btn bg-gradient-primary text-light"></input>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div style="padding:2%">
                    <!-- Left side columns -->
                    <div>
                        <div class="" style="overflow:scroll;">
                            <table id="example" class="table table-striped"
                                style="overflow:scroll;  width:100%; min-width: max-content;">
                                <thead>
                                    <tr style="background:#02B4C3;">
                                        <th scope="col" class="text-center text-white">Sr.No</th>
                                        <th scope="col" class="text-center text-white">News Title</th>
                                        <th scope="col" class="text-center text-white">Active Status</th>
                                        <th scope="col" class="text-center text-white">News Date</th>
                                        <th scope="col" class="text-center text-white">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if news_data %}
                                    {% for r in news_data %}
                                    <tr>

                                        <td class="text-center">{{ forloop.counter }}</td>
                                        <td class="text-center">{{ r.title }}</td>
                                        <td class="text-center"> 
                                            {% if r.is_active %}
                                            <span class="badge bg-success">Publish</span>
                                            {% else %}
                                            <span class="badge bg-danger">Not Publish</span>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">{{ r.date }}</td>

                                        <td>
                                            <center>
                                                <a href="{% url "admin_news_details" r.id %}" class="btn btn-primary px-3">Read More</a>
                                                <a href="{% url "admin_update_news" r.id %}" class="btn btn-warning px-3">Edit</a>
                                                <a href="{% url "admin_delete_news" r.id %}" class="btn btn-danger px-3">Delete</a>
                                            </center>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}

                                    {% endif %}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div><!-- End Left side columns -->
            </div>
        </div><!-- End Left side columns -->

    </section>
 

</main><!-- End #main -->



<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script> 
    $(document).ready(function() {
        $('.summernote').each(function() {
            const customHeight = $(this).data('height') || 300; // Default to 300 if no data-height
            $(this).summernote({
                height: customHeight,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['insert', ['link', 'picture']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ]
            });
        });
    });
</script>


{% endblock content %}

WebAdmin/templates/admin_update_news.html
{% extends "admin_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    #id_content {
        height: 100px;
    } 

    .update_news{
        
        border-radius: 20px;
        background-color: #fff;
    }
     
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Update Events</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->
   
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12">
                 
                 <br><br>
                <div class="update_news p-4" id="update_news">
                         
                    <form id="update_news_form"  enctype="multipart/form-data"  method="post">
                        {% csrf_token %} 
                        <div class="row">
                            <div class="col-sm-12">
                                {{form|crispy}}
                            </div>
                            
                        </div>
                        <center>
                        <input type="submit" id="update_form_submit_button" class="btn btn-primary mt-2 px-5" value="Update">

                        <button class="btn btn-secondary mt-2 px-4"  id="update_form_loading_button" type="button" style="display: none;"  disabled>
                            <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                            Loading....
                          </button>
                        </center>
                    </form>
                </div>

            </div>
             
        </div>
    </div>
 
    </script>

</main><!-- End #main -->

<script>
    
    function submitUpdateEventForm() {
        document.getElementById('update_form_submit_button').style.display = 'none';
        document.getElementById('update_form_loading_button').style.display = 'block';
        document.getElementById('update_news_form').submit();
    }
</script>


<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script> 
    $(document).ready(function() {
        $('.summernote').each(function() {
            const customHeight = $(this).data('height') || 300; // Default to 300 if no data-height
            $(this).summernote({
                height: customHeight,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['insert', ['link', 'picture']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ]
            });
        });
    });
</script>

{% endblock content %}